### ISSUE TITLE
Any chance you could add an official open source license?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [zpasternack/CustomTextView#1]
Thanks for sharing this!

Any chance you could add an official license like the MIT or BSD license to this repo?  That would just make it more clear for those that might want to use it.

Best wishes and good luck.  :-)

**Comment by zpasternack** [comment]
Sure, good idea. Added info for Modified BSD License.

**Comment by iosdev-republicofapps** [comment]
Awesome, thanks!  :-)
